services:
  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    restart: unless-stopped
    ports:
      - 3100:3100
      - 7946
      - 9095

  tempo:
    image: grafana/tempo:2.7.2
    container_name: tempo
    restart: unless-stopped
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml

  mimir:
    image: grafana/mimir:2.14.3
    container_name: mimir
    restart: unless-stopped
    ports:
      - 9090:9090
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_FORM_LOGIN=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
      - tempo

  promtail:
    image: grafana/promtail:3.3.2
    container_name: promtail
    restart: unless-stopped
    command: ["-config.file=/etc/promtail/config.yaml"]
    volumes:
      - /var/log:/var/log
